-- Supabase setup for the discussion presentation system.
-- This version allows public browser access with the publishable key,
-- so anyone who knows the page URL can operate the presentation.
-- Tighten RLS or add admin authentication later if needed.

create table if not exists public.discussion_presentation_pages (
  id bigint generated by default as identity primary key,
  team_id integer not null check (team_id between 1 and 10),
  page_no integer not null check (page_no >= 1),
  title text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (team_id, page_no)
);

create table if not exists public.discussion_presentation_state (
  id integer primary key check (id = 1),
  mode text not null default 'waiting' check (mode in ('waiting', 'show', 'finale')),
  current_team_id integer null check (current_team_id between 1 and 10),
  current_page_no integer not null default 1 check (current_page_no >= 1),
  timer_state text not null default 'reset' check (timer_state in ('reset', 'playing', 'paused')),
  timer_remain_secs integer not null default 300 check (timer_remain_secs >= 0),
  timer_last_action_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_discussion_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_discussion_pages_updated_at on public.discussion_presentation_pages;
create trigger set_discussion_pages_updated_at
before update on public.discussion_presentation_pages
for each row
execute function public.set_discussion_updated_at();

drop trigger if exists set_discussion_state_updated_at on public.discussion_presentation_state;
create trigger set_discussion_state_updated_at
before update on public.discussion_presentation_state
for each row
execute function public.set_discussion_updated_at();

insert into public.discussion_presentation_state (
  id,
  mode,
  current_page_no,
  timer_state,
  timer_remain_secs,
  timer_last_action_at
)
values (
  1,
  'waiting',
  1,
  'reset',
  300,
  timezone('utc', now())
)
on conflict (id) do nothing;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.discussion_presentation_pages to anon, authenticated;
grant select, insert, update on public.discussion_presentation_state to anon, authenticated;
grant usage, select on sequence public.discussion_presentation_pages_id_seq to anon, authenticated;

alter table public.discussion_presentation_pages enable row level security;
alter table public.discussion_presentation_state enable row level security;

drop policy if exists "public read presentation pages" on public.discussion_presentation_pages;
create policy "public read presentation pages"
on public.discussion_presentation_pages
for select
to anon, authenticated
using (true);

drop policy if exists "public insert presentation pages" on public.discussion_presentation_pages;
create policy "public insert presentation pages"
on public.discussion_presentation_pages
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update presentation pages" on public.discussion_presentation_pages;
create policy "public update presentation pages"
on public.discussion_presentation_pages
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete presentation pages" on public.discussion_presentation_pages;
create policy "public delete presentation pages"
on public.discussion_presentation_pages
for delete
to anon, authenticated
using (true);

drop policy if exists "public read presentation state" on public.discussion_presentation_state;
create policy "public read presentation state"
on public.discussion_presentation_state
for select
to anon, authenticated
using (true);

drop policy if exists "public insert presentation state" on public.discussion_presentation_state;
create policy "public insert presentation state"
on public.discussion_presentation_state
for insert
to anon, authenticated
with check (id = 1);

drop policy if exists "public update presentation state" on public.discussion_presentation_state;
create policy "public update presentation state"
on public.discussion_presentation_state
for update
to anon, authenticated
using (id = 1)
with check (id = 1);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'discussion_presentation_pages'
  ) then
    alter publication supabase_realtime add table public.discussion_presentation_pages;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'discussion_presentation_state'
  ) then
    alter publication supabase_realtime add table public.discussion_presentation_state;
  end if;
end
$$;
