-- Secure Supabase setup for the discussion presentation system.
-- Raw presentation data is private. Only the derived public display row is readable with the publishable key.

create table if not exists public.discussion_presentation_pages (
  id bigint generated by default as identity primary key,
  team_id integer not null check (team_id between 1 and 10),
  page_no integer not null check (page_no >= 1),
  title text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (team_id, page_no)
);

create table if not exists public.discussion_presentation_state (
  id integer primary key check (id = 1),
  mode text not null default 'waiting' check (mode in ('waiting', 'show', 'finale')),
  current_team_id integer null check (current_team_id between 1 and 10),
  current_page_no integer not null default 1 check (current_page_no >= 1),
  waiting_message text not null default '발표를 대기 중입니다.',
  timer_state text not null default 'reset' check (timer_state in ('reset', 'playing', 'paused')),
  timer_remain_secs integer not null default 300 check (timer_remain_secs >= 0),
  timer_last_action_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.discussion_public_display (
  id integer primary key check (id = 1),
  status text not null default 'waiting' check (status in ('waiting', 'show', 'nodata', 'finale')),
  team_id integer null check (team_id between 1 and 10),
  current_page integer not null default 1 check (current_page >= 1),
  total_pages integer not null default 1 check (total_pages >= 1),
  title text not null default '',
  content text not null default '',
  waiting_message text not null default '발표를 대기 중입니다.',
  timer_state text not null default 'reset' check (timer_state in ('reset', 'playing', 'paused')),
  timer_remain_secs integer not null default 300 check (timer_remain_secs >= 0),
  timer_last_action_at timestamptz not null default timezone('utc', now()),
  finale_titles jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.discussion_presentation_state
add column if not exists waiting_message text not null default '발표를 대기 중입니다.';

alter table public.discussion_public_display
add column if not exists waiting_message text not null default '발표를 대기 중입니다.';

create or replace function public.set_discussion_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_discussion_pages_updated_at on public.discussion_presentation_pages;
create trigger set_discussion_pages_updated_at
before update on public.discussion_presentation_pages
for each row
execute function public.set_discussion_updated_at();

drop trigger if exists set_discussion_state_updated_at on public.discussion_presentation_state;
create trigger set_discussion_state_updated_at
before update on public.discussion_presentation_state
for each row
execute function public.set_discussion_updated_at();

insert into public.discussion_presentation_state (
  id,
  mode,
  current_page_no,
  waiting_message,
  timer_state,
  timer_remain_secs,
  timer_last_action_at
)
values (
  1,
  'waiting',
  1,
  '발표를 대기 중입니다.',
  'reset',
  300,
  timezone('utc', now())
)
on conflict (id) do nothing;

insert into public.discussion_public_display (
  id,
  status,
  current_page,
  total_pages,
  title,
  content,
  waiting_message,
  timer_state,
  timer_remain_secs,
  timer_last_action_at,
  finale_titles
)
values (
  1,
  'waiting',
  1,
  1,
  '',
  '',
  '발표를 대기 중입니다.',
  'reset',
  300,
  timezone('utc', now()),
  '[]'::jsonb
)
on conflict (id) do nothing;

create or replace function public.refresh_discussion_public_display()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.discussion_presentation_state%rowtype;
  v_status text := 'waiting';
  v_team_id integer := null;
  v_current_page integer := 1;
  v_total_pages integer := 1;
  v_title text := '';
  v_content text := '';
  v_waiting_message text := '발표를 대기 중입니다.';
  v_finale_titles jsonb := '[]'::jsonb;
  v_page record;
begin
  select *
  into v_state
  from public.discussion_presentation_state
  where id = 1;

  if not found then
    v_state.id := 1;
    v_state.mode := 'waiting';
    v_state.current_team_id := null;
    v_state.current_page_no := 1;
    v_state.waiting_message := '발표를 대기 중입니다.';
    v_state.timer_state := 'reset';
    v_state.timer_remain_secs := 300;
    v_state.timer_last_action_at := timezone('utc', now());
  end if;

  v_waiting_message := coalesce(nullif(trim(v_state.waiting_message), ''), '발표를 대기 중입니다.');

  v_current_page := greatest(coalesce(v_state.current_page_no, 1), 1);

  if v_state.mode = 'finale' then
    v_status := 'finale';

    select coalesce(
      jsonb_agg(
        jsonb_build_object('team', team_id, 'title', title)
        order by team_id, page_no
      ),
      '[]'::jsonb
    )
    into v_finale_titles
    from public.discussion_presentation_pages
    where nullif(trim(title), '') is not null;
  elsif v_state.mode = 'show' and v_state.current_team_id is not null then
    v_team_id := v_state.current_team_id;

    select count(*)
    into v_total_pages
    from public.discussion_presentation_pages
    where team_id = v_team_id;

    v_total_pages := greatest(coalesce(v_total_pages, 0), 1);

    if v_total_pages = 1 then
      select page_no, title, content
      into v_page
      from public.discussion_presentation_pages
      where team_id = v_team_id
      order by page_no
      limit 1;

      if found then
        v_status := 'show';
        v_current_page := v_page.page_no;
        v_title := v_page.title;
        v_content := v_page.content;
      else
        v_status := 'nodata';
      end if;
    else
      select page_no, title, content
      into v_page
      from public.discussion_presentation_pages
      where team_id = v_team_id
        and page_no = v_current_page
      limit 1;

      if not found then
        select page_no, title, content
        into v_page
        from public.discussion_presentation_pages
        where team_id = v_team_id
        order by page_no
        limit 1;
      end if;

      if found then
        v_status := 'show';
        v_current_page := v_page.page_no;
        v_title := v_page.title;
        v_content := v_page.content;
      else
        v_status := 'nodata';
        v_current_page := 1;
      end if;
    end if;
  end if;

  insert into public.discussion_public_display (
    id,
    status,
    team_id,
    current_page,
    total_pages,
    title,
    content,
    waiting_message,
    timer_state,
    timer_remain_secs,
    timer_last_action_at,
    finale_titles,
    updated_at
  )
  values (
    1,
    v_status,
    v_team_id,
    v_current_page,
    v_total_pages,
    v_title,
    v_content,
    v_waiting_message,
    coalesce(v_state.timer_state, 'reset'),
    coalesce(v_state.timer_remain_secs, 300),
    coalesce(v_state.timer_last_action_at, timezone('utc', now())),
    v_finale_titles,
    timezone('utc', now())
  )
  on conflict (id) do update
  set status = excluded.status,
      team_id = excluded.team_id,
      current_page = excluded.current_page,
      total_pages = excluded.total_pages,
      title = excluded.title,
      content = excluded.content,
      waiting_message = excluded.waiting_message,
      timer_state = excluded.timer_state,
      timer_remain_secs = excluded.timer_remain_secs,
      timer_last_action_at = excluded.timer_last_action_at,
      finale_titles = excluded.finale_titles,
      updated_at = excluded.updated_at;
end;
$$;

create or replace function public.refresh_discussion_public_display_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_discussion_public_display();
  return null;
end;
$$;

drop trigger if exists refresh_public_display_on_pages on public.discussion_presentation_pages;
create trigger refresh_public_display_on_pages
after insert or update or delete on public.discussion_presentation_pages
for each statement
execute function public.refresh_discussion_public_display_trigger();

drop trigger if exists refresh_public_display_on_state on public.discussion_presentation_state;
create trigger refresh_public_display_on_state
after insert or update or delete on public.discussion_presentation_state
for each statement
execute function public.refresh_discussion_public_display_trigger();

revoke all on public.discussion_presentation_pages from anon, authenticated;
revoke all on public.discussion_presentation_state from anon, authenticated;
revoke all on sequence public.discussion_presentation_pages_id_seq from anon, authenticated;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.discussion_presentation_pages to service_role;
grant select, insert, update on public.discussion_presentation_state to service_role;
grant select on public.discussion_public_display to anon, authenticated, service_role;
grant usage, select on sequence public.discussion_presentation_pages_id_seq to service_role;

alter table public.discussion_presentation_pages enable row level security;
alter table public.discussion_presentation_state enable row level security;
alter table public.discussion_public_display enable row level security;

drop policy if exists "public read presentation pages" on public.discussion_presentation_pages;
drop policy if exists "public insert presentation pages" on public.discussion_presentation_pages;
drop policy if exists "public update presentation pages" on public.discussion_presentation_pages;
drop policy if exists "public delete presentation pages" on public.discussion_presentation_pages;
drop policy if exists "public read presentation state" on public.discussion_presentation_state;
drop policy if exists "public insert presentation state" on public.discussion_presentation_state;
drop policy if exists "public update presentation state" on public.discussion_presentation_state;
drop policy if exists "public read discussion public display" on public.discussion_public_display;

create policy "public read discussion public display"
on public.discussion_public_display
for select
to anon, authenticated
using (id = 1);

do $$
begin
  if exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'discussion_presentation_pages'
  ) then
    alter publication supabase_realtime drop table public.discussion_presentation_pages;
  end if;
end
$$;

do $$
begin
  if exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'discussion_presentation_state'
  ) then
    alter publication supabase_realtime drop table public.discussion_presentation_state;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'discussion_public_display'
  ) then
    alter publication supabase_realtime add table public.discussion_public_display;
  end if;
end
$$;

select public.refresh_discussion_public_display();
